spring.application.name=backend

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/loanapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:loanapp}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:loanapp}

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

loan.max-age=70