spring.application.name=backend

server.port=8080

# Database configuration uses hardcoded defaults for showing purpose.
# Would normally set up a .env file but that would complicate it for the tester.
spring.datasource.url=jdbc:postgresql://localhost:5432/loanapp
spring.datasource.username=loanapp
spring.datasource.password=loanapp

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

loan.max-age=70
loan.base-interest=1.1
